from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

NAME_LENGTH = 255


class GameInfoModel(Base):
    __tablename__ = 'games'

    ID = Column(Integer, primary_key=True)
    GAME_ID = Column(String(12))
    GAME_DT = Column(Integer)
    GAME_CT = Column(Integer)
    GAME_DY = Column(String(9))
    START_GAME_TM = Column(Integer)
    DH_FL = Column(String(1))
    DAYNIGHT_PARK_CD = Column(String(1))
    AWAY_TEAM_ID = Column(String(NAME_LENGTH))
    HOME_TEAM_ID = Column(String(NAME_LENGTH))
    PARK_ID = Column(String(NAME_LENGTH))
    AWAY_START_PIT_ID = Column(String(NAME_LENGTH))
    HOME_START_PIT_ID = Column(String(NAME_LENGTH))
    BASE4_UMP_ID = Column(String(NAME_LENGTH))
    BASE1_UMP_ID = Column(String(NAME_LENGTH))
    BASE2_UMP_ID = Column(String(NAME_LENGTH))
    BASE3_UMP_ID = Column(String(NAME_LENGTH))
    LF_UMP_ID = Column(String(NAME_LENGTH))
    RF_UMP_ID = Column(String(NAME_LENGTH))
    ATTEND_PARK_CT = Column(Integer)
    SCORER_RECORD_ID = Column(String(NAME_LENGTH))
    TRANSLATOR_RECORD_ID = Column(String(NAME_LENGTH))
    INPUTTER_RECORD_ID = Column(String(NAME_LENGTH))
    INPUT_RECORD_TS = Column(String(NAME_LENGTH))
    EDIT_RECORD_TS = Column(String(NAME_LENGTH))
    METHOD_RECORD_CD = Column(String(NAME_LENGTH))
    PITCHES_RECORD_CD = Column(String(1))
    TEMP_PARK_CT = Column(Integer)
    WIND_DIRECTION_PARK_CD = Column(Integer)
    WIND_SPEED_PARK_CT = Column(Integer)
    FIELD_PARK_CD = Column(Integer)
    PRECIP_PARK_CD = Column(Integer)
    SKY_PARK_CD = Column(Integer)
    MINUTES_GAME_CT = Column(Integer)
    INN_CT = Column(Integer)
    AWAY_SCORE_CT = Column(Integer)
    HOME_SCORE_CT = Column(Integer)
    AWAY_HITS_CT = Column(Integer)
    HOME_HITS_CT = Column(Integer)
    AWAY_ERR_CT = Column(Integer)
    HOME_ERR_CT = Column(Integer)
    AWAY_LOB_CT = Column(Integer)
    HOME_LOB_CT = Column(Integer)
    WIN_PIT_ID = Column(String(NAME_LENGTH))
    LOSE_PIT_ID = Column(String(NAME_LENGTH))
    SAVE_PIT_ID = Column(String(NAME_LENGTH))
    GWRBI_BAT_ID = Column(String(NAME_LENGTH))
    AWAY_LINEUP1_BAT_ID = Column(String(NAME_LENGTH))
    AWAY_LINEUP1_FLD_CD = Column(Integer)
    AWAY_LINEUP2_BAT_ID = Column(String(NAME_LENGTH))
    AWAY_LINEUP2_FLD_CD = Column(Integer)
    AWAY_LINEUP3_BAT_ID = Column(String(NAME_LENGTH))
    AWAY_LINEUP3_FLD_CD = Column(Integer)
    AWAY_LINEUP4_BAT_ID = Column(String(NAME_LENGTH))
    AWAY_LINEUP4_FLD_CD = Column(Integer)
    AWAY_LINEUP5_BAT_ID = Column(String(NAME_LENGTH))
    AWAY_LINEUP5_FLD_CD = Column(Integer)
    AWAY_LINEUP6_BAT_ID = Column(String(NAME_LENGTH))
    AWAY_LINEUP6_FLD_CD = Column(Integer)
    AWAY_LINEUP7_BAT_ID = Column(String(NAME_LENGTH))
    AWAY_LINEUP7_FLD_CD = Column(Integer)
    AWAY_LINEUP8_BAT_ID = Column(String(NAME_LENGTH))
    AWAY_LINEUP8_FLD_CD = Column(Integer)
    AWAY_LINEUP9_BAT_ID = Column(String(NAME_LENGTH))
    AWAY_LINEUP9_FLD_CD = Column(Integer)
    HOME_LINEUP1_BAT_ID = Column(String(NAME_LENGTH))
    HOME_LINEUP1_FLD_CD = Column(Integer)
    HOME_LINEUP2_BAT_ID = Column(String(NAME_LENGTH))
    HOME_LINEUP2_FLD_CD = Column(Integer)
    HOME_LINEUP3_BAT_ID = Column(String(NAME_LENGTH))
    HOME_LINEUP3_FLD_CD = Column(Integer)
    HOME_LINEUP4_BAT_ID = Column(String(NAME_LENGTH))
    HOME_LINEUP4_FLD_CD = Column(Integer)
    HOME_LINEUP5_BAT_ID = Column(String(NAME_LENGTH))
    HOME_LINEUP5_FLD_CD = Column(Integer)
    HOME_LINEUP6_BAT_ID = Column(String(NAME_LENGTH))
    HOME_LINEUP6_FLD_CD = Column(Integer)
    HOME_LINEUP7_BAT_ID = Column(String(NAME_LENGTH))
    HOME_LINEUP7_FLD_CD = Column(Integer)
    HOME_LINEUP8_BAT_ID = Column(String(NAME_LENGTH))
    HOME_LINEUP8_FLD_CD = Column(Integer)
    HOME_LINEUP9_BAT_ID = Column(String(NAME_LENGTH))
    HOME_LINEUP9_FLD_CD = Column(Integer)
    AWAY_FINISH_PIT_ID = Column(String(NAME_LENGTH))
    HOME_FINISH_PIT_ID = Column(String(NAME_LENGTH))
